let
    Source = Folder.Files("C:\Users\hashi\Documents\Programming\Projects\skymetrics\data\raw"),
    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"YEAR", Int64.Type}, {"QUARTER", Int64.Type}, {"MONTH", Int64.Type}, {"DAY_OF_MONTH", Int64.Type}, {"FL_DATE", type datetime}, {"OP_UNIQUE_CARRIER", type text}, {"ORIGIN", type text}, {"ORIGIN_CITY_NAME", type text}, {"ORIGIN_STATE_ABR", type text}, {"DEST_AIRPORT_SEQ_ID", Int64.Type}, {"DEST", type text}, {"DEST_CITY_NAME", type text}, {"DEST_STATE_ABR", type text}, {"CRS_DEP_TIME", Int64.Type}, {"DEP_TIME", Int64.Type}, {"DEP_DELAY", Int64.Type}, {"DEP_DELAY_NEW", Int64.Type}, {"DEP_DEL15", Int64.Type}, {"CRS_ARR_TIME", Int64.Type}, {"ARR_TIME", Int64.Type}, {"ARR_DELAY", Int64.Type}, {"ARR_DELAY_NEW", Int64.Type}, {"ARR_DEL15", Int64.Type}, {"CANCELLED", Int64.Type}, {"CANCELLATION_CODE", type any}, {"DIVERTED", Int64.Type}, {"CRS_ELAPSED_TIME", Int64.Type}, {"ACTUAL_ELAPSED_TIME", Int64.Type}, {"AIR_TIME", Int64.Type}, {"FLIGHTS", Int64.Type}, {"DISTANCE", Int64.Type}, {"CARRIER_DELAY", Int64.Type}, {"WEATHER_DELAY", Int64.Type}, {"NAS_DELAY", Int64.Type}, {"SECURITY_DELAY", Int64.Type}, {"LATE_AIRCRAFT_DELAY", Int64.Type}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"YEAR", "Year"}, {"QUARTER", "Quarter"}, {"MONTH", "Month"}, {"DAY_OF_MONTH", "DayOfMonth"}, {"FL_DATE", "FlightDate"}, {"OP_UNIQUE_CARRIER", "CarrierCode"}, {"ORIGIN", "OriginAirport"}, {"ORIGIN_CITY_NAME", "OriginCity"}, {"ORIGIN_STATE_ABR", "OriginState"}, {"DEST", "DestAirport"}, {"DEST_CITY_NAME", "DestCity"}, {"DEST_STATE_ABR", "DestState"}, {"CRS_DEP_TIME", "ScheduledDepTime"}, {"DEP_TIME", "ActualDepTime"}, {"DEP_DELAY", "DepDelay"}, {"DEP_DEL15", "DepDelayed15"}, {"CRS_ARR_TIME", "ScheduledArrTime"}, {"ARR_TIME", "ActualArrTime"}, {"ARR_DELAY", "ArrDelay"}, {"ARR_DEL15", "ArrDelayed15"}, {"CANCELLED", "IsCancelled"}, {"CANCELLATION_CODE", "CancellationCode"}, {"DIVERTED", "IsDiverted"}, {"CRS_ELAPSED_TIME", "ScheduledElapsedTime"}, {"ACTUAL_ELAPSED_TIME", "ActualElapsedTime"}, {"AIR_TIME", "AirTime"}, {"FLIGHTS", "FlightCount"}, {"DISTANCE", "Distance"}, {"CARRIER_DELAY", "CarrierDelay"}, {"WEATHER_DELAY", "WeatherDelay"}, {"NAS_DELAY", "NASDelay"}, {"SECURITY_DELAY", "SecurityDelay"}, {"LATE_AIRCRAFT_DELAY", "LateAircraftDelay"}}),
    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"DEP_DELAY_NEW", "ARR_DELAY_NEW", "DEST_AIRPORT_SEQ_ID"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"FlightDate", type date}, {"DepDelay", type number}, {"ArrDelay", type number}, {"CarrierDelay", type number}, {"WeatherDelay", type number}, {"NASDelay", type number}, {"SecurityDelay", type number}, {"LateAircraftDelay", type number}, {"CancellationCode", type text}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type1",{"Source.Name"}),
    #"Added Custom" = Table.AddColumn(#"Removed Columns1", "DayOfWeek", each Date.DayOfWeekName([FlightDate])),
    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"DayOfWeek", type text}})
in
    #"Changed Type2"